import type { ExcalidrawScene } from '@yohaku/rich-content/src/lexical/portable/excalidraw/index.ts'

type Defaults = {
  angle: number
  backgroundColor: string
  fillStyle:
    | 'solid'
    | 'hachure'
    | 'cross-hatch'
    | 'zigzag'
    | 'zigzag-line'
    | 'dots'
    | 'dashed'
  opacity: number
  roughness: number
  strokeColor: string
  strokeStyle: 'solid' | 'dashed' | 'dotted'
  strokeWidth: number
}

const D: Defaults = {
  angle: 0,
  backgroundColor: 'transparent',
  fillStyle: 'solid',
  opacity: 100,
  roughness: 1,
  strokeColor: '#1e1e1e',
  strokeStyle: 'solid',
  strokeWidth: 2,
}

function wrap(
  elements: Array<Record<string, unknown>>,
  bg = '#ffffff',
): ExcalidrawScene {
  const stamped = elements.map((el, idx) => ({
    ...D,
    seed: 1000 + idx,
    isDeleted: false,
    groupIds: [],
    boundElements: null,
    link: null,
    locked: false,
    updated: 1,
    version: 1,
    versionNonce: idx + 1,
    ...el,
  })) as unknown as ExcalidrawScene['elements']
  return {
    type: 'excalidraw',
    version: 2,
    source: 'yohaku-demo',
    elements: stamped,
    appState: { viewBackgroundColor: bg },
    files: {},
  }
}

export const fixtures: Array<{
  description: string
  key: string
  scene: ExcalidrawScene
  title: string
}> = [
  {
    key: 'rect-basic',
    title: 'Rectangle — defaults',
    description: 'Plain rectangle, transparent background, default stroke.',
    scene: wrap([
      { id: 'r1', type: 'rectangle', x: 40, y: 40, width: 200, height: 120 },
    ]),
  },
  {
    key: 'rect-rounded-filled',
    title: 'Rectangle — rounded + hachure fill',
    description: 'Roundness type 3 (proportional), hachure fill, thick stroke.',
    scene: wrap([
      {
        id: 'r2',
        type: 'rectangle',
        x: 40,
        y: 40,
        width: 240,
        height: 140,
        backgroundColor: '#a5d8ff',
        fillStyle: 'hachure',
        strokeWidth: 3,
        roundness: { type: 3 },
      },
    ]),
  },
  {
    key: 'ellipse-cross',
    title: 'Ellipse — cross-hatch',
    description: 'Cross-hatch fill, custom stroke color.',
    scene: wrap([
      {
        id: 'e1',
        type: 'ellipse',
        x: 40,
        y: 40,
        width: 220,
        height: 160,
        strokeColor: '#1971c2',
        backgroundColor: '#a5d8ff',
        fillStyle: 'cross-hatch',
      },
    ]),
  },
  {
    key: 'diamond-solid',
    title: 'Diamond — solid fill',
    description: 'Solid fill, accent stroke.',
    scene: wrap([
      {
        id: 'd1',
        type: 'diamond',
        x: 40,
        y: 40,
        width: 200,
        height: 200,
        strokeColor: '#e03131',
        backgroundColor: '#ffc9c9',
        fillStyle: 'solid',
      },
    ]),
  },
  {
    key: 'line-styles',
    title: 'Line — solid / dashed / dotted',
    description: 'Three straight lines stacked.',
    scene: wrap([
      {
        id: 'l1',
        type: 'line',
        x: 40,
        y: 40,
        width: 240,
        height: 0,
        strokeStyle: 'solid',
        points: [
          [0, 0],
          [240, 0],
        ],
      },
      {
        id: 'l2',
        type: 'line',
        x: 40,
        y: 80,
        width: 240,
        height: 0,
        strokeStyle: 'dashed',
        points: [
          [0, 0],
          [240, 0],
        ],
      },
      {
        id: 'l3',
        type: 'line',
        x: 40,
        y: 120,
        width: 240,
        height: 0,
        strokeStyle: 'dotted',
        points: [
          [0, 0],
          [240, 0],
        ],
      },
    ]),
  },
  {
    key: 'arrow-heads',
    title: 'Arrow — head variants',
    description: 'arrow / triangle / triangle_outline / dot / bar.',
    scene: wrap([
      ...['arrow', 'triangle', 'triangle_outline', 'dot', 'bar'].map(
        (head, i) => ({
          id: `a${i}`,
          type: 'arrow',
          x: 40,
          y: 40 + i * 36,
          width: 240,
          height: 0,
          endArrowhead: head,
          points: [
            [0, 0],
            [240, 0],
          ],
        }),
      ),
    ]),
  },
  {
    key: 'arrow-curve',
    title: 'Arrow — curved (roundness 2)',
    description: 'Multi-point curved arrow.',
    scene: wrap([
      {
        id: 'ac',
        type: 'arrow',
        x: 40,
        y: 40,
        width: 280,
        height: 160,
        strokeColor: '#2f9e44',
        strokeWidth: 2,
        endArrowhead: 'arrow',
        roundness: { type: 2 },
        points: [
          [0, 0],
          [120, 160],
          [280, 80],
        ],
      },
    ]),
  },
  {
    key: 'freedraw',
    title: 'Freedraw — scribble',
    description: 'Hand-drawn squiggle path.',
    scene: wrap([
      {
        id: 'f1',
        type: 'freedraw',
        x: 40,
        y: 80,
        width: 280,
        height: 80,
        strokeColor: '#f08c00',
        strokeWidth: 3,
        simulatePressure: true,
        pressures: [],
        points: Array.from(
          { length: 60 },
          (_, i) => [i * 5, Math.sin(i / 3) * 30 + 40] as [number, number],
        ),
      },
    ]),
  },
  {
    key: 'text-fonts',
    title: 'Text — Excalifont / Helvetica / Cascadia',
    description: 'Three lines, each in a different fontFamily id.',
    scene: wrap([
      {
        id: 't1',
        type: 'text',
        x: 40,
        y: 30,
        width: 320,
        height: 36,
        text: 'Excalifont hand',
        fontSize: 28,
        fontFamily: 5,
        textAlign: 'left',
        verticalAlign: 'top',
        baseline: 23,
      },
      {
        id: 't2',
        type: 'text',
        x: 40,
        y: 90,
        width: 320,
        height: 30,
        text: 'Helvetica normal',
        fontSize: 24,
        fontFamily: 2,
        textAlign: 'left',
        verticalAlign: 'top',
        baseline: 20,
      },
      {
        id: 't3',
        type: 'text',
        x: 40,
        y: 150,
        width: 320,
        height: 30,
        text: 'Cascadia mono(){}',
        fontSize: 22,
        fontFamily: 3,
        textAlign: 'left',
        verticalAlign: 'top',
        baseline: 18,
      },
    ]),
  },
  {
    key: 'text-cjk',
    title: 'Text — CJK with LXGW WenKai Screen',
    description:
      'Chinese characters fall back to LXGW WenKai Screen (handwriting). Mixed-script lines fall back per-glyph via unicode-range.',
    scene: wrap([
      {
        id: 'cjk1',
        type: 'text',
        x: 40,
        y: 30,
        width: 480,
        height: 40,
        text: '霞鹜文楷 — handwriting',
        fontSize: 28,
        fontFamily: 5,
        textAlign: 'left',
        verticalAlign: 'top',
        baseline: 23,
      },
      {
        id: 'cjk2',
        type: 'text',
        x: 40,
        y: 90,
        width: 480,
        height: 90,
        text: '春眠不觉晓，\n处处闻啼鸟。\n夜来风雨声，花落知多少。',
        fontSize: 22,
        fontFamily: 5,
        textAlign: 'left',
        verticalAlign: 'top',
        baseline: 18,
        lineHeight: 1.4,
      },
      {
        id: 'cjk3',
        type: 'text',
        x: 40,
        y: 230,
        width: 480,
        height: 28,
        text: 'Mixed 中英 mix 123 你好 hello',
        fontSize: 20,
        fontFamily: 5,
        textAlign: 'left',
        verticalAlign: 'top',
        baseline: 16,
      },
    ]),
  },
  {
    key: 'text-align',
    title: 'Text — alignment + multi-line',
    description: 'Left / center / right + a multi-line block.',
    scene: wrap([
      {
        id: 'ta1',
        type: 'text',
        x: 40,
        y: 30,
        width: 360,
        height: 36,
        text: 'Left aligned',
        fontSize: 22,
        fontFamily: 5,
        textAlign: 'left',
        verticalAlign: 'top',
        baseline: 18,
      },
      {
        id: 'ta2',
        type: 'text',
        x: 40,
        y: 80,
        width: 360,
        height: 36,
        text: 'Centered',
        fontSize: 22,
        fontFamily: 5,
        textAlign: 'center',
        verticalAlign: 'top',
        baseline: 18,
      },
      {
        id: 'ta3',
        type: 'text',
        x: 40,
        y: 130,
        width: 360,
        height: 36,
        text: 'Right aligned',
        fontSize: 22,
        fontFamily: 5,
        textAlign: 'right',
        verticalAlign: 'top',
        baseline: 18,
      },
      {
        id: 'ta4',
        type: 'text',
        x: 40,
        y: 200,
        width: 360,
        height: 90,
        text: 'Multi-line\nsecond row\nthird row',
        fontSize: 20,
        fontFamily: 5,
        textAlign: 'left',
        verticalAlign: 'top',
        baseline: 16,
        lineHeight: 1.3,
      },
    ]),
  },
  {
    key: 'flowchart',
    title: 'Flowchart — boxes + arrows + labels',
    description: 'Mini end-to-end scene: three nodes wired by arrows.',
    scene: wrap([
      {
        id: 'fc-box-a',
        type: 'rectangle',
        x: 40,
        y: 40,
        width: 160,
        height: 70,
        backgroundColor: '#d0ebff',
        fillStyle: 'hachure',
        roundness: { type: 3 },
      },
      {
        id: 'fc-text-a',
        type: 'text',
        x: 60,
        y: 64,
        width: 120,
        height: 26,
        text: 'Request',
        fontSize: 20,
        fontFamily: 5,
        textAlign: 'center',
        verticalAlign: 'top',
        baseline: 18,
      },
      {
        id: 'fc-box-b',
        type: 'diamond',
        x: 280,
        y: 30,
        width: 160,
        height: 100,
        backgroundColor: '#fff3bf',
        fillStyle: 'solid',
        strokeColor: '#f59f00',
      },
      {
        id: 'fc-text-b',
        type: 'text',
        x: 300,
        y: 64,
        width: 120,
        height: 26,
        text: 'Auth?',
        fontSize: 20,
        fontFamily: 5,
        textAlign: 'center',
        verticalAlign: 'top',
        baseline: 18,
        strokeColor: '#a76700',
      },
      {
        id: 'fc-box-c',
        type: 'rectangle',
        x: 520,
        y: 40,
        width: 160,
        height: 70,
        backgroundColor: '#d3f9d8',
        fillStyle: 'cross-hatch',
        roundness: { type: 3 },
      },
      {
        id: 'fc-text-c',
        type: 'text',
        x: 540,
        y: 64,
        width: 120,
        height: 26,
        text: 'Response',
        fontSize: 20,
        fontFamily: 5,
        textAlign: 'center',
        verticalAlign: 'top',
        baseline: 18,
      },
      {
        id: 'fc-arrow-1',
        type: 'arrow',
        x: 200,
        y: 75,
        width: 80,
        height: 0,
        endArrowhead: 'arrow',
        points: [
          [0, 0],
          [80, 0],
        ],
      },
      {
        id: 'fc-arrow-2',
        type: 'arrow',
        x: 440,
        y: 75,
        width: 80,
        height: 0,
        endArrowhead: 'arrow',
        points: [
          [0, 0],
          [80, 0],
        ],
      },
      {
        id: 'fc-box-d',
        type: 'rectangle',
        x: 280,
        y: 200,
        width: 160,
        height: 70,
        backgroundColor: '#ffd8a8',
        fillStyle: 'hachure',
        strokeColor: '#d9480f',
        roundness: { type: 3 },
      },
      {
        id: 'fc-text-d',
        type: 'text',
        x: 300,
        y: 224,
        width: 120,
        height: 26,
        text: 'Reject',
        fontSize: 20,
        fontFamily: 5,
        textAlign: 'center',
        verticalAlign: 'top',
        baseline: 18,
        strokeColor: '#9b2c00',
      },
      {
        id: 'fc-arrow-3',
        type: 'arrow',
        x: 360,
        y: 130,
        width: 0,
        height: 70,
        endArrowhead: 'arrow',
        strokeStyle: 'dashed',
        points: [
          [0, 0],
          [0, 70],
        ],
      },
    ]),
  },
  {
    key: 'placeholders',
    title: 'Image / Frame / Embed — placeholders',
    description:
      'Missing image data + frame + embeddable show labelled placeholders.',
    scene: wrap([
      {
        id: 'img-missing',
        type: 'image',
        x: 40,
        y: 40,
        width: 200,
        height: 120,
        fileId: 'missing',
        status: 'pending',
      },
      {
        id: 'frame-1',
        type: 'frame',
        x: 280,
        y: 40,
        width: 220,
        height: 120,
        name: 'Frame A',
      },
      {
        id: 'embed-1',
        type: 'embeddable',
        x: 40,
        y: 200,
        width: 460,
        height: 120,
      },
    ]),
  },
]
